#!/bin/bash

# program to output a system information page
# comments added by a second contributor
# another contribution from an outside contributor

REPORT_HTML='sys-info-page.html'

rm -f "$REPORT_HTML"
# trap "rm -f $REPORT_HTML" EXIT


report1() {
    echo "generating report1"
    return 0
}

report2() {
    echo "generating report2"
    return 0
}

report3() {
    echo "generating report3"
    return 0
}


TITLE="System Information Report for $HOSTNAME"
CURRENT_TIME=$(date)
TIME_STAMP="Generated $CURRENT_TIME, by $USER"

cat <<EOF > $REPORT_HTML
<HTML>
	<HEAD>
		<TITLE>$TITLE</TITLE>
	</HEAD>
	<BODY>
		<H1>$TITLE</H1>
		<P>$TIME_STAMP</P>
		$(report1)
		$(report2)
	</BODY>
</HTML>
EOF

exit 0
