#!/bin/bash

# program to output a system information page

REPORTHTML='sys-info-page.html'

rm -f "$REPORTHTML"
# trap "rm -f $REPORTHTML" EXIT

cat <<EOF > $REPORTHTML
<HTML>
	<HEAD>
		<TITLE> Some Title </TITLE>
	</HEAD>
	<BODY>
		Page Body
	</BODY>
</HTML>
EOF

exit 0
